### ISSUE TITLE
BufferOverFlowException

### ISSUE THREAD

**Issue by teddytree** [00-Evan/shattered-pixel-dungeon-gdx#28]
Game crashed on desktop with the following stack trace:

Exception in thread "LWJGL Application" java.nio.BufferOverflowException
        at java.nio.DirectFloatBufferU.put(DirectFloatBufferU.java:363)
        at java.nio.FloatBuffer.put(FloatBuffer.java:859)
        at com.watabou.noosa.BitmapTextMultiline.updateVertices(BitmapTextMultiline.java:126)
        at com.watabou.noosa.BitmapText.draw(BitmapText.java:79)
        at com.watabou.noosa.Group.draw(Group.java:78)
        at com.watabou.noosa.Group.draw(Group.java:78)
        at com.watabou.noosa.Group.draw(Group.java:78)
        at com.watabou.noosa.Game.draw(Game.java:221)
        at com.watabou.noosa.Game.render(Game.java:148)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

last printed message: 

GAME: There is something else here.

**Comment by 00-Evan** [comment]
Closing this issue as this repo is now deprecated and I am not planning on fixing any issues which are specific to it. Feel free to make a new issue in the main repository if you encounter this issue again.
