### ISSUE TITLE
Freeze caused by enemy on chest?

### ISSUE THREAD

**Issue by BozoDel** [00-Evan/shattered-pixel-dungeon-gdx#31]
So I was playing the other day and the game froze. From what I recall, I killed an enemy on top of a chest, then clicked it.

I always run the game from a terminal, and this is what came out:

> (...)
GAME: You defeated gnoll brute.
GAME: You now have gold.
GAME: There is something else here.
Exception in thread "LWJGL Application" java.nio.BufferOverflowException
	at java.nio.DirectFloatBufferU.put(DirectFloatBufferU.java:363)
	at java.nio.FloatBuffer.put(FloatBuffer.java:859)
	at com.watabou.noosa.BitmapTextMultiline.updateVertices(BitmapTextMultiline.java:126)
	at com.watabou.noosa.BitmapText.draw(BitmapText.java:79)
	at com.watabou.noosa.Group.draw(Group.java:78)
	at com.watabou.noosa.Group.draw(Group.java:78)
	at com.watabou.noosa.Group.draw(Group.java:78)
	at com.watabou.noosa.Game.draw(Game.java:221)
	at com.watabou.noosa.Game.render(Game.java:148)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

I was running version 0.6.0b, on Linux Mint 18 MATE 64-bit. java -version gives me:

> java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by 00-Evan** [comment]
Closing this issue as this repo is now deprecated and I am not planning on fixing any issues which are specific to it. Feel free to make a new issue in the main repository if you encounter this issue again.
